version: "3.9"

services:
  ssh-honeypot:
    build: ./ssh
    container_name: ssh_honeypot
    networks:
      honeynet_vlan10:
        ipv4_address: 192.168.10.10
    ports:
      - "2222:2222" 

  http-honeypot:
    build: ./http
    container_name: http_honeypot
    networks:
      honeynet_vlan10:
        ipv4_address: 192.168.10.20
    ports:
      - "80:80"

  ftp-honeypot:
    build: ./ftp
    container_name: ftp_honeypot
    networks:
      honeynet_vlan10:
        ipv4_address: 192.168.10.30
    ports:
      - "21:21"

networks:
  honeynet_vlan10:
    external: true
